#!/usr/bin/env Rscript
## Write a complete, valid miniature dataset and a config that points at it.
##
## Reading a format spec and guessing is how people lose a day.  This writes one
## of every object the pipeline needs, small enough to open and inspect, and a
## config that runs end to end on it -- so "what should my tree look like?" is
## answered by str() on a real one.
source(file.path(dirname(sub("^--file=", "", commandArgs(FALSE)[grep("^--file=", commandArgs(FALSE))][1])), "boot.R"))
a <- args_parse(list(out = "cfTREBLE_example", celltypes = "8", samples = "3",
                     cpgs = "400", chunks = "2", seed = "1"))
set.seed(as.integer(a$seed))
out <- normalizePath(a$out, mustWork = FALSE)
ref <- file.path(out, "reference")
dir.create(file.path(ref, "chunks"), recursive = TRUE, showWarnings = FALSE)

n_ct <- as.integer(a$celltypes); n_s <- as.integer(a$samples)
n_cpg <- as.integer(a$cpgs); n_ch <- as.integer(a$chunks)

## ---- sample_list: named list, one entry per cell type ---------------------------
ct <- sprintf("CellType%02d", seq_len(n_ct))
sample_list <- setNames(lapply(ct, function(x) sprintf("%s_rep%d", x, seq_len(n_s))), ct)
saveRDS(sample_list, file.path(ref, "sample_list.rds"))

## ---- tree: children + parent ----------------------------------------------------
## Leaves MUST be nodes 1..n_ct, in the same order as sample_list.  Internal
## nodes follow, the root is last, and the root is its own parent.
hc <- hclust(dist(matrix(rnorm(n_ct * 20), n_ct)), "ward.D2"); hc$labels <- ct
tr <- hclust_to_tree(hc, ct)
saveRDS(tr$children, file.path(ref, "tree_children.rds"))
saveRDS(tr$parent,   file.path(ref, "tree_parent.rds"))

## ---- priors ---------------------------------------------------------------------
mp_l <- c(0.06, 0.55, 0.39)
saveRDS(list(mu = c(-1.42, 1.55, 0.66), sigma = c(0.24, 0.29, 0.65),
             lambda = mp_l / sum(mp_l)), file.path(ref, "mu_prior.rds"))
sp_pi <- c(.052, .094, .254, .076, .251, .150, .054, .027, .041)
saveRDS(list(grid = c(0, .10, .15, .20, .25, .35, .50, .60, 1.00),
             pi   = sp_pi / sum(sp_pi)),          # must sum to 1; `check` enforces it
        file.path(ref, "sigma_prior.rds"))

## ---- count matrices: rows = CpG, columns = unlist(sample_list) -------------------
truth <- simulate_truth(tr, n_cpg * n_ch, marker_frac = 0.35)
groups <- sample_groups(sample_list)
ref_dat <- simulate_reference(truth, groups, depth = 40)
rows <- split(seq_len(n_cpg * n_ch), rep(seq_len(n_ch), each = n_cpg))
for (k in seq_len(n_ch)) {
  saveRDS(ref_dat$M[rows[[k]], , drop = FALSE], file.path(ref, "chunks", sprintf("M_%d.rds", k)))
  saveRDS(ref_dat$N[rows[[k]], , drop = FALSE], file.path(ref, "chunks", sprintf("N_%d.rds", k)))
}

## ---- a plasma sample with known composition --------------------------------------
props <- c(0.5, 0.2, rep(0.3 / (n_ct - 2), n_ct - 2)); props <- props / sum(props)
names(props) <- ct
simulate_plasma(truth, props, 60, file.path(ref, "plasma_example.beta"))
saveRDS(props, file.path(ref, "plasma_example_truth.rds"))

## ---- a config that points at all of it --------------------------------------------
cfgf <- file.path(out, "example.yaml")
writeLines(c(
  "# Generated by `cftreble example`.  Everything it refers to is in reference/.",
  paste0("base:      ", out), "work: work", "run_tag:   example",
  paste0("readonly:  ", ref), "",
  "tree:", "  from_lists:",
  "    children:   ${readonly}/tree_children.rds",
  "    parent:     ${readonly}/tree_parent.rds",
  "    celltypes:  ${readonly}/sample_list.rds", "",
  "priors:", "  mu:     ${readonly}/mu_prior.rds",
  "  sigma:  ${readonly}/sigma_prior.rds",
  "  sigma_truncate: auto", "  gh_points: 5", "",
  "data:", "  sample_list: ${readonly}/sample_list.rds",
  "  m_chunks:    ${readonly}/chunks/M_%d.rds",
  "  n_chunks:    ${readonly}/chunks/N_%d.rds",
  paste0("  chunks:      [", paste(seq_len(n_ch), collapse = ", "), "]"),
  paste0("  chunk_stride: ", n_cpg), "",
  "likelihood:", paste0("  batch_size: ", n_cpg), "  block_size: 100",
  paste0("  ncores: ", max(1L, min(8L, parallel::detectCores() - 1L))),
  "  prefilter: false", "  em_sample_per_chunk: 0", "",
  "prior_em:", "  tol: 1.0e-6", "  max_iter: 300", "  cache: false", "",
  "markers:", "  lowest_p: 0.90", "  min_read_depth: 15", "  min_rel_distance: 1.64",
  "  min_abs_distance: 0.30", "  min_abs_distance_T0: 0.30",
  "  min_IQR_target: 0.15", "  min_IQR_offtarget: 0.12", "  alpha_cap: 150000",
  "  slack: 5", "  max_per_celltype: 2000", "  max_per_node: 2000",
  "  strict_celltypes: []", "  strict_rel_distance: 1.96",
  "  subject_specific: true", "",
  "subject:", "  weight_coverage: 0.9999", "",
  "deconvolve:", "  beta_n_cpg: null", "  drop_sample_cols: []", "",
  "slurm:", "  account: YOUR_ALLOCATION", "  partition: RM-shared",
  "  ntasks: 8", '  time: "02:00:00"'), cfgf)

cat(sprintf("\nWrote a complete example under %s\n\n", out))
cat("  reference/sample_list.rds        named list, %d cell types x %d samples\n" |>
    sprintf(n_ct, n_s))
cat(sprintf("  reference/tree_children.rds      %d nodes; leaves 1..%d are c(i), internal are c(left, right)\n",
            tr$n_node, tr$n_leaf))
cat(sprintf("  reference/tree_parent.rds        %d integers; parent[%d] = %d (the root is its own parent)\n",
            tr$n_node, tr$n_node, tr$n_node))
cat("  reference/mu_prior.rds           list($mu, $sigma, $lambda), 3 components\n")
cat("  reference/sigma_prior.rds        list($grid, $pi), grid ascending and starting at 0\n")
cat(sprintf("  reference/chunks/{M,N}_k.rds     %d chunks of %d CpGs x %d samples (integer counts)\n",
            n_ch, n_cpg, length(groups)))
cat("  reference/plasma_example.beta    uint8 (methylated, total) pairs, one per CpG\n")
cat("  reference/plasma_example_truth.rds  the proportions it was mixed at\n")
cat(sprintf("  example.yaml                     a config pointing at all of it\n\n"))
cat("Look at them:\n")
cat(sprintf("  Rscript -e 'str(readRDS(\"%s/reference/tree_children.rds\"))'\n", out))
cat("\nThen run the pipeline on it:\n")
cat(sprintf("  cftreble --config %s check\n", cfgf))
cat(sprintf("  cftreble --config %s tree\n", cfgf))
cat(sprintf("  cftreble --config %s likelihood --chunk 1\n", cfgf))
cat("  ... prior, markers, signature, subject, deconvolve\n\n")
