#!/usr/bin/env Rscript
## Regenerate NAMESPACE from the top-level function definitions in R/.
##
## Imports are explicit on purpose.  A blanket import() of the packages the
## original scripts attached produced nine name collisions (expm, grad, hessian,
## jacobian, lu, sqrtm, logm, tril, triu) resolved only by load order -- none of
## which this code actually calls.  Naming what is used removes the ambiguity.
P <- normalizePath(file.path(dirname(sub("^--file=", "",
  commandArgs(FALSE)[grep("^--file=", commandArgs(FALSE))][1])), ".."))
## Every top-level binding, not just functions -- constants like LIK_FIELDS_MIN
## are part of the interface too, and omitting them fails only at run time.
fns <- unlist(lapply(list.files(file.path(P, "R"), "[.]R$", full.names = TRUE), function(f) {
  e <- parse(f)
  nm <- vapply(e, function(x) if (is.call(x) && as.character(x[[1]]) %in% c("<-", "=") &&
      is.name(x[[2]])) as.character(x[[2]]) else NA_character_, "")
  nm[!is.na(nm)] }))
## %||% is in base as of R 4.4 -- exporting ours would mask it for every user.
fns <- setdiff(fns, "%||%")
fns <- sort(unique(fns[!grepl("^[.]", fns)]))
imports <- list(
  `data.table`  = c("fread", "fwrite", "data.table", "transpose", "setDT", "rbindlist"),
  parallel      = c("mclapply", "detectCores"),
  pbv           = "pbvnorm",
  pracma        = "gaussHermite",
  RhpcBLASctl   = "blas_set_num_threads",
  mixsqp        = "mixsqp",
  yaml          = "read_yaml",
  jsonlite      = c("write_json", "fromJSON"),
  stats         = c("pnorm", "qnorm", "dnorm", "qbeta", "rbeta", "rbinom", "rpois",
                    "rnorm", "rgamma", "runif", "sd", "median", "quantile", "cor",
                    "dist", "hclust", "complete.cases", "setNames", "aggregate"),
  utils         = c("head", "tail", "read.csv", "write.csv"))
lines <- c("# Generated by tools/make_namespace.R -- do not edit by hand",
           sprintf('export("%s")', fns), "")
for (p in names(imports))
  lines <- c(lines, sprintf('importFrom("%s", "%s")', p, imports[[p]]))
writeLines(lines, file.path(P, "NAMESPACE"))
cat("NAMESPACE: ", length(fns), " exports, ",
    sum(lengths(imports)), " explicit imports from ", length(imports), " packages\n", sep = "")
